Jenkinsfile finally done

diff --git a/cicd/Jenkins/Jenkinsfile b/cicd/Jenkins/Jenkinsfile
--- a/cicd/Jenkins/Jenkinsfile
+++ b/cicd/Jenkins/Jenkinsfile
@@ -112,29 +112,519 @@ pipeline {
     }
 
     stages {
-
-      stage('PR Build') {
-        when {
-            beforeAgent true
-            not { branch 'master' }
-        } 
-        // agent {
-        // //   dockerfile {
-        //     // filename 'Dockerfile'
-        //     // dir 'cicd/docker/helm'
-        //     label 'Docker-enabled'
-        // //   }
-        // }
+      stage('Summary') {
         steps {
           script {
             sh script: """
-                scripts/dockerCI.sh alias
-                source ~/.bash_profile
-                ls -lah
-                chi test
-                chi test-e2e
-            """, label: "Running Chi from its container as always" 
+                echo "PROJECT_NAME: ${PROJECT_NAME}"
+                echo "DOCKER_REPO: ${DOCKER_REPO}"
+                echo "GIT_BRANCH: ${GIT_BRANCH}"
+                echo "GIT_COMMIT: ${GIT_COMMIT}"
+                echo "BRANCH_NAME: ${BRANCH_NAME}"
+                echo "COMMIT_ID: ${COMMIT_ID}"
+                echo "PULL_REQUEST: ${PULL_REQUEST}"
+                echo "CHANGE_ID: ${env.CHANGE_ID}"
+                echo "IMAGE_NAME: ${IMAGE_NAME}"
+                echo "IMAGE_TAG: ${IMAGE_TAG}"                        
+            """, label: "Details summary"
           }
+        }
+      }
+      stage('Authorize - Prod only') {
+        when {
+          branch 'master'
+        }
+        steps {
+          script {
+            jslDeploymentControlKnob()
+          }
+        }
+      }
+      stage('Static Code Analysis') {
+        parallel {
+          stage('Linting') {
+            when {
+              beforeAgent true
+              not { branch 'master' }
+            }
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                //registryUrl DOCKER_REGISTRY
+                //registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+              }
+            }
+            steps {
+              script{
+                // jslYarnWrapper('install')
+                // jslNpmWrapper('run lint')
+                // jslNpmWrapper('run prettier:checker')
+                echo "No full linting implemented in repo, skipping until linting is implemented globally"
+              }
+            }
+          }
+          stage('DevSecOps') {
+            when {
+              beforeAgent true
+              not { branch 'master' }
+            }
+            steps {
+              script {
+                jslGitHubSecurityAlert()
+              }
+            }
+          }
+          stage('Package Version') {
+            steps {
+              script {
+                sh(script: """
+                    git whatchanged -1 --format=oneline
+                    git diff origin/master package.json | grep '"version":' || echo No package.json changes
+                    git diff origin/master package-lock.json | grep '"version":' || echo No package-lock.json changes
+                    if [ \$(git diff origin/master package.json | grep '"version":' | wc -l) -eq 2 ]; then
+                        if [ \$(git diff origin/master package-lock.json | grep '"version":' | wc -l) -lt 2 ]; then
+                            echo "##########################################################################################"
+                            echo "### VERSION UPDATE package-lock.json IS REQUIRED ALONG WITH package.json               ###"
+                            echo "##########################################################################################"
+                            exit -1
+                        fi
+                        if [ \$(git whatchanged -1 --format=oneline | wc -l) -gt 3 ]; then
+                            echo "##########################################################################################"
+                            echo "### PACKAGE VERSION INCREASED ALONG WITH OTHER CHANGES - TESTS ABORTED                 ###"
+                            echo "### A SEPARATE PULL REQUEST MUST BE CREATED TO BUMP UP PACKAGE VERSION                 ###"
+                            echo "##########################################################################################"
+                            exit -1
+                        fi
+                    fi
+                    git diff HEAD~1 HEAD package.json
+                    rm -rf version_bump
+                    if [ \$(git diff HEAD~1 HEAD package.json | grep '"version":' | wc -l) -eq 2 ]; then
+                      echo -n "yes" > version_bump
+                    else
+                      echo -n "no" > version_bump
+                    fi
+                    cat version_bump
+                    echo "All good."
+                """, label: "Package version validation")
+                stash name: "VERSION_BUMP", includes: "version_bump"
+              }
+            }
+          }
+        }
+      }
+      stage('PR Build') {
+        parallel {
+          stage ('Building Chi') {
+            when {
+                beforeAgent true
+                not { branch 'master' }
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                jslYarnWrapper('install')
+                jslNpmWrapper('run build')
+              }
+            }
+          }
+          stage ('Building Custom elements') {
+            when {
+                beforeAgent true
+                not { branch 'master' }
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                dir('src/custom-elements') {
+                  jslYarnWrapper('install')
+                  jslNpmWrapper('run build')
+                }
+              }
+            }
+          }
+          stage ('Building Chi-vue') {
+            when {
+                beforeAgent true
+                not { branch 'master' }
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                dir('src/chi-vue') {
+                  jslYarnWrapper('install')
+                  jslNpmWrapper('run build:component')
+                }
+              }
+            }
+          }
+        }
+      }
+      stage('Build for Production') {
+        parallel {
+          stage ('Building Chi') {
+            when {
+                beforeAgent true
+                branch 'master'
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                jslYarnWrapper('install')
+                jslNpmWrapper('run build')
+              }
+            }
+          }
+          stage ('Building Custom elements') {
+            when {
+                beforeAgent true
+                branch 'master'
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                dir('src/custom-elements') {
+                  jslYarnWrapper('install')
+                  jslNpmWrapper('run build')
+                }
+              }
+            }
+          }
+          stage ('Building Chi-vue') {
+            when {
+                beforeAgent true
+                branch 'master'
+            } 
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            steps {
+              script {
+                dir('src/chi-vue') {
+                  jslYarnWrapper('install')
+                  jslNpmWrapper('run build:component')
+                }
+              }
+            }
+          }
+        }
+      }
+      stage ('Tests') {
+        parallel {
+          stage ('Unit Testing') {
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+                // registryUrl DOCKER_REGISTRY
+                // registryCredentialsId DOCKER_CREDENTIALS
+              }
+            }
+            when {
+              beforeAgent true
+              not { branch 'master' }
+            }
+            steps {
+              script {
+                sh script: """
+                  whoami
+                  ls -lrta
+                  rm -rf reports test/bitmaps_test
+                  mkdir -p reports/html_report/non_responsive
+                  mkdir -p reports/html_report/non_responsive_ce
+                  mkdir -p reports/html_report/responsive
+                  cp -a config/backstop_data/bitmaps_reference/non_responsive reports/html_report/non_responsive_ce/bitmaps_reference
+                  cp -a config/backstop_data/bitmaps_reference/non_responsive reports/html_report/non_responsive/bitmaps_reference
+                  cp -a config/backstop_data/bitmaps_reference/responsive reports/html_report/responsive/bitmaps_reference
+                """, label: "Copying config files"
+                jslYarnWrapper('cache clean')
+                jslNpmWrapper('run test')
+                echo "This will run Unit tests - Disabled until I fix permissions issues."
+              }
+            }
+          }
+          stage ('E2E Testing') {
+            // agent {
+
+            // }
+            when {
+              beforeAgent true
+              not { branch 'master' }
+            }
+            steps {
+              // script {
+                echo "This will run E2E tests, when NPX is added to the JSL"
+              // }
+            }
+          }
+        }
+      }
+      stage('Coverage'){
+        when {
+          beforeAgent true
+          not { branch 'master' }
+        }
+        agent {
+          dockerfile {
+            filename 'Dockerfile'
+            dir 'cicd/docker/cypress'
+            label 'Docker-enabled'
+            // registryUrl DOCKER_REGISTRY
+            // registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+          }
+        }
+        steps {
+          script {
+            // jslYarnWrapper('install')
+            // sh "rm -rf .nyc_output*"
+            // sh "rm -rf coverage/"
+            // unstash name: "NYC_OUTPUT_UNIT"
+            // unstash name: "NYC_OUTPUT_E2E"
+            // jslNpmWrapper('run cover:merge')
+            // archiveArtifacts artifacts: '.nyc_output/**'
+            // jslNpmWrapper('run cover:report:jenkins || echo Error when evaluating coverage report!')
+            // stash name: "COVERAGE", includes: "coverage/**"
+            // archiveArtifacts artifacts: 'coverage/**'
+            // jslQualityGateCodeCoverage('./cicd/docker/SonarQube/sonar-project.properties')
+            echo "Coverage will be enabled as soon as Sonarqube is available for CHI"
+          }
+        }
+      }
+      stage('Coverage upload to Sonarqube'){
+        agent {
+          dockerfile {
+            filename 'Dockerfile'
+            dir 'cicd/docker/cypress'
+            label 'Docker-enabled'
+            // registryUrl DOCKER_REGISTRY
+            // registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+          }
+        }
+        steps {
+          script {
+            // try {
+            //   unstash name: "COVERAGE"
+            // }  catch (Exception e) {
+            //   echo "No coverage data"
+            // }
+            // jslSonarQubeStaticAnalysis('./cicd/docker/SonarQube/sonar-project.properties', env.SONARQUBE_CREDENTIALS)
+            echo "Coverage upload will be enabled as soon as Sonarqube is available for CHI"
+          }
+        }
+      }
+      stage('Quality Gate Check'){
+        agent {
+          dockerfile {
+            filename 'Dockerfile'
+            dir 'cicd/docker/cypress'
+            label 'Docker-enabled'
+            // registryUrl DOCKER_REGISTRY
+            // registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+          }
+        }
+        steps {
+          script {
+            // jslQualityGate()
+            echo "Quality gate check will be enabled as soon as Sonarqube is available for CHI"
+          }
+        }
+      }
+      stage('Smoke Tests') {
+        when {
+          beforeAgent true
+          allOf {
+            not { branch 'master' }
+            expression{ return currentBuild.currentResult.toLowerCase() == "success" }
+          }
+        }
+        agent {
+          dockerfile {
+            filename 'Dockerfile'
+            dir 'cicd/docker/cypress'
+            label 'Docker-enabled'
+            // registryUrl DOCKER_REGISTRY
+            // registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+          }
+        }
+        steps {
+          script {
+            // unstash name: "E2E_REPORTS"
+            // def cypress_url = parseIngressUrl()
+            // echo "Deployment is reachable at ${cypress_url}"
+            // jslNpmWrapper('ci')
+            // jslNpmWrapper("run test:smoke:jenkins -- --url ${cypress_url} || echo Smoke Tests failed!")
+            // echo "Smoke Tests completed"
+            // jslPublishTestResults('tests/e2e/reports/*xml')
+            // stash name: "E2E_REPORTS", includes: "tests/e2e/reports/**"
+
+            // def VIDEOS_AVAILABLE = -1
+            // VIDEOS_AVAILABLE = sh(script: "ls tests/e2e/videos/*", returnStatus: true)
+            // if (VIDEOS_AVAILABLE == 0) {
+            //   archiveArtifacts artifacts: 'tests/e2e/videos/**/*'
+            // }
+            // def SCREENSHOTS_AVAILABLE = -1
+            // SCREENSHOTS_AVAILABLE = sh(script: "ls tests/e2e/screenshots/*", returnStatus: true)
+            // if (SCREENSHOTS_AVAILABLE == 0) {
+            //   archiveArtifacts artifacts: 'tests/e2e/screenshots/**/*'
+            echo "Depends on NPX being available for testing on the JSL"
+          }
+        }
+      }
+      stage('Adoption Stats') {
+        agent {
+          dockerfile {
+            filename 'Dockerfile'
+            dir 'cicd/docker/jira'
+            label 'Docker-enabled'
+            // registryUrl DOCKER_REGISTRY
+            // registryCredentialsId DOCKER_LOGIN_CREDENTIALS
+          }
+        }
+        steps {
+          script {
+            // try {
+            //   unstash name: "E2E_REPORTS"
+            //   jslAdoptionMain('tests/e2e/reports/*xml')
+            // } catch (Exception e) {
+            //   try {
+            //     unstash name: "UNIT_REPORTS"
+            //     jslAdoptionMain('tests/unit/reports/*xml')
+            //     echo "No E2E results found, reporting only unit"
+            //   } catch (Exception exc) {
+            //     echo "No E2E or Unit results found, reporting simple unit"
+            //     unstash name: "TEST_PROD"
+            //     jslAdoptionMain('test-results.xml')
+            //   }
+            echo "Adoption stats will be enabled as soon as E2E testing is enabled"
+          }
+        }
+      }
+      stage('Version check & Publish to GitHub') {
+        when {
+          beforeAgent true
+          expression {
+            unstash name: "VERSION_BUMP"
+            def versionBump = readFile file: "version_bump"
+            echo "Publish condition: GIT_BRANCH is _${env.GIT_BRANCH.trim().toLowerCase()}_"
+            echo "Publish condition: currentResult is _${currentBuild.currentResult.toLowerCase()}_"
+            echo "Publish condition: versionBump is _${versionBump.trim()}_"
+            return versionBump.trim() == "yes" && currentBuild.currentResult.toLowerCase() == "success" && ['origin/master', 'origin/main', 'master', 'main'].contains(env.GIT_BRANCH.trim().toLowerCase())
+          }
+        }
+        stages {
+          stage('GitHub Release') {
+            agent {
+              dockerfile {
+                filename 'Dockerfile'
+                dir 'cicd/docker/cypress'
+                label 'Docker-enabled'
+              }
+            }
+            steps {
+              script {
+                // def packageJson = readJSON file: 'package.json'
+                // def tagName = "${packageJson.version}"
+                // echo "Release tag is ${tagName}"
+                // def releaseId = jslGitHubReleaseGetId(tagName)
+                // sh "touch do_release"
+                // if (releaseId == null) {
+                //   def committishName = GIT_BRANCH
+                //   if (GIT_BRANCH.startsWith('origin/')) {
+                //     committishName = GIT_BRANCH.split("/")[1]
+                //   }
+                //   releaseId = jslGitHubReleaseCreate(tagName, committishName)
+                //   if (releaseId == null) {
+                //     throw new Exception("There was an error publishing the release")
+                //   }
+                //   sh "echo -n yes > do_release"
+                // } else {
+                //   echo "A release already exists for ${tagName}"
+                //   sh "echo -n no > do_release"
+                // }
+                // stash name: "DO_RELEASE", includes: "do_release"
+                echo "Active development, will activate as soon as this works"
+              }
+            }
+          }
+        }
+      }
+      stage ('Publish to S3') {
+        parallel {
+          stage ('Publish Dev/Beta build') {
+            when {
+              beforeAgent true
+              not { branch 'master' }
+            }
+            steps {
+              // script {
+                echo "This will publish dev build to S3"
+              // }
+            }
+          }
+          stage ('Publish Prod Build') {
+            when {
+              beforeAgent true
+              branch 'master'
+            }
+            steps {
+              // script {
+                echo "This will publish Prod build to S3 & CDN"
+              // }
+            }
+          }            
+        }
+      }
+      stage ('Cleaning...') {
+        steps {
+          echo "Pipeline finished!"
         }
       }
     }
